export const LIST_PRODUCTS = "LIST_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART"
export const DELETE_WITH_HANDLE_CHANGE = "DELETE_WITH_HANDLE_CHANGE"
export const SEARCH_PRODUCT = "SEARCH_PRODUCT"